### ISSUE TITLE
能给出此项目所使用库的版本吗？我觉得此问题是库的版本不同导致的。

### ISSUE THREAD

**Issue by kullferr** [AiXing-w/Local_QA_based_on_llm#1]
AttributeError: 'NoneType' object has no attribute 'similarity_search'
`Traceback (most recent call last):
  File "d:\Python\Python311\Lib\site-packages\gradio\queueing.py", line 521, in process_events
    response = await route_utils.call_process_api(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Python\Python311\Lib\site-packages\gradio\route_utils.py", line 276, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Python\Python311\Lib\site-packages\gradio\blocks.py", line 1923, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Python\Python311\Lib\site-packages\gradio\blocks.py", line 1509, in call_function
    prediction = await anyio.to_thread.run_sync(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Python\Python311\Lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Python\Python311\Lib\site-packages\anyio\_backends\_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "d:\Python\Python311\Lib\site-packages\anyio\_backends\_asyncio.py", line 859, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Python\Python311\Lib\site-packages\gradio\utils.py", line 832, in wrapper
    response = f(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^
  File "D:\LocalQA_webui\main.py", line 61, in bot
    info = augment_prompt(db, query)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\LocalQA_webui\utils\model_process.py", line 46, in augment_prompt
    similar_docs = db.similarity_search(query, k=k)
                   ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'similarity_search'`

**Comment by kullferr** [comment]
我已经进入了问答页面，但在发送问题后，页面会显示“错误”，然后在终端会报告以上错误

**Comment by AiXing-w** [comment]
requirements已上传
